# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=128, unique=True)),
                ('contact_numbers', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True)),
                ('contacts', models.ManyToManyField(to='smscontacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=128, unique=True)),
                ('template_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
